version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootdev
    ports:
      - 27017:27017
  app:
    container_name: padelnuestro
    build: .
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    volumes:
      - ./:/home/node/app

version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootdev
    ports:
      - 27017:27017
  app:
    container_name: padelnuestro
    build: .
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    volumes:
      - ./:/home/node/app
